import { Navigation } from "@/components/Navigation";
import { cn } from "@/lib/utils";
import { Web3Provider } from "@/providers/Web3Provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        roboto.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Web3Provider>
          <Navigation />
          <div className="flex min-h-0 flex-1 flex-col pt-14 pb-[calc(5rem+env(safe-area-inset-bottom))] md:pb-0">
            {children}
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
